id: P000527
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W25139
  title: ལྷ་ལྡན་ཇོ་བོ་རིན་པོ་ཆེའི་བྱུང་བ
  author: ''
  volumes:
    08f102284fbd4a9a95b28cbd4269919e:
      image_group_id: I1GS55161
      title: ''
      volume_number: 1
      total_pages: 49
      base_file: v001.txt
