id: P000527
initial_creation_type: ocr
source_metadata:
  id: bdr:W25139
  title: ལྷ་ལྡན་ཇོ་བོ་རིན་པོ་ཆེའི་བྱུང་བ
  author: ''
  volumes:
    08f102284fbd4a9a95b28cbd4269919e:
      image_group_id: I1GS55161
      title: ''
      volume_number: 1
      total_pages: 49
      base_file: v001.txt
ebook_metadata:
  title: ལྷ་ལྡན་ཇོ་བོ་རིན་པོ་ཆེའི་བྱུང་བ
  author: ''
  sku: P000527
  cover: cover.jpg
  layers:
  - pagination
